### ISSUE TITLE
Release 0.3.0 On crates.io

### ISSUE THREAD

**Issue by Enduriel** [dagrs-dev/dagrs#65]
Any reason the latest tag of this Crate isn't on crates.io? This project is exactly what I was looking for and I actually gave up on finding something like and started working on something like it before stumbling into it during a random search, maybe there's some SEO to do here because I think this project should be a lot more popular than it currently is as this sort of thing is very useful.

**Comment by genedna** [comment]
Hi @Enduriel ，

After discussing this crate with several developers who use it, we all agreed that the current architecture is quite complex and that we should focus more on the core features. Therefore, I have established a new organization to work on the new version. If you like using this crate, consider referencing it directly from Git in your `Cargo.toml` until I deem it stable enough to release an updated version.

For now, my main focus is on the [Mega](https://github.com/web3infra-foundation/mega) project. If you have time and ideas, you can submit PRs to **dagrs** to add the desired features.

**Comment by tomgroenwoldt** [comment]
Hi @genedna,

the company I work for is interested in keeping this crate actively maintained. We do have resources to support this and we would like to discuss further development with you in a call. Does that sound good to you?
